# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0acb3463b4fbc4d5c81000ad975acf61f4cc67edc9f48f911099f8f12b8cd359ea330864da331d726faeea37800a8bfc5b34f8da186564a75e35f2a48fc244b2

test:
  secret_key_base: 3ea3b30f26f231668ddce2c81ca26bd146ed8ceae346131ed6544b74fe6772f5db3817db1d7e13be8870cadeaa11dde0ec643fe471b47a0deaf9932ec7f2677a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
